Algoritmo "verificaNumeros"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Jailson  Costa dos Santos
// Descrição   : Verifica se  número é positivo ou negativo
// Autor(a)    : maria Fernanda Falcão de Lima
// Data atual  : 04/09/2025
Var
numero: Real

Inicio
Escreva("Digite o número a ser verificado: ")
   Leia(numero)
   Se numero < 0 entao
      Escreval("O número é negativo")
   senao
        Escreval("O número é positivo")
   fimse
Fimalgoritmo